"""
Definition of models.
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ListEmployeeType(models.Model):
    employee_type_id = models.AutoField(primary_key=True)
    employee_type = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class ListAgencyType(models.Model):
    agency_type_id = models.AutoField(primary_key=True)
    agency_type = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class ListTimeZone(models.Model):
    time_zone_id = models.AutoField(primary_key=True)
    time_zone = models.CharField(max_length=50)
    system_default = models.BooleanField(default=0)
    active = models.BooleanField(default=1)

class ListLanguage(models.Model):
    language_id = models.AutoField(primary_key=True)
    language = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class ListMaritalStatus(models.Model):
    marital_status_id = models.AutoField(primary_key=True)
    marital_status = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class ListEthnicity(models.Model):
    ethnicity_id = models.AutoField(primary_key=True)
    ethnicity = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class ListClientStatus(models.Model):
    client_status_id = models.AutoField(primary_key=True)
    client_status = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class ListStaffStatus(models.Model):
    staff_status_id = models.AutoField(primary_key=True)
    staff_status = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class ListReligion(models.Model):
    religion_id = models.AutoField(primary_key=True)
    religion = models.CharField(max_length=50)
    active = models.BooleanField(default=1)

class Agency(models.Model):
    agency_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    #federal_id?????? what the fuck is this thing for? do we need this?
    website = models.CharField(max_length=100, null=True)
    primary_contact_name = models.CharField(max_length=100)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    zipcode = models.CharField(max_length=10, null=True)
    office_number = models.CharField(max_length=15, null=True)
    other_number = models.CharField(max_length=15, null=True)
    fax = models.CharField(max_length=15, null=True)
    time_zone = models.ForeignKey(ListTimeZone)
    created_date = models.DateField()
    created_by = models.CharField(max_length=50, null=True)
    modified_date = models.DateField(null=True)
    modified_by = models.CharField(max_length=50, null=True)
    longitude = models.CharField(max_length=50, null=True)
    latitude = models.CharField(max_length=50, null=True)
    active = models.BooleanField(default=1)

class ReferralType(models.Model):
	referral_type_id = models.AutoField(primary_key=True)
	referral_type = models.CharField(max_length=50)
	agency = models.ForeignKey(Agency)
	active = models.BooleanField(default=1)

class UserProfile(models.Model):
    user_profile_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, unique=True)
    employee_id = models.CharField(max_length=50, null=True)
    employee_type = models.ForeignKey(ListEmployeeType, null=True)
    gender = models.CharField(max_length=10, null=True)
    language = models.ForeignKey(ListLanguage, null=True)
    ssn = models.CharField(max_length=9, null=True)
    dob = models.DateField(null=True)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    zipcode = models.CharField(max_length=10, null=True)
    home_phone = models.CharField(max_length=15, null=True)
    mobile_phone = models.CharField(max_length=15, null=True)
    hire_date = models.DateField(null=True)
    termination_date = models.DateField(null=True)
    staff_status = models.ForeignKey(ListStaffStatus, null=True)
    status_date = models.DateField(null=True)
    status_note = models.CharField(max_length=400, null=True)
    created_date = models.DateField()
    created_by = models.CharField(max_length=50, null=True)
    modified_date = models.DateField(null=True)
    modified_by = models.CharField(max_length=50, null=True)
    velocicare_admin = models.BooleanField(default=0)
    active = models.BooleanField(default=1)

class ReferralCompany(models.Model):
    referral_company_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    referral_type = models.ForeignKey(ReferralType, null=True)
    website = models.CharField(max_length=100, null=True)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    zipcode = models.CharField(max_length=10, null=True)
    office_number = models.CharField(max_length=15, null=True)
    other_number = models.CharField(max_length=15, null=True)
    fax = models.CharField(max_length=15, null=True)
    email = models.CharField(max_length=50, null=True)
    created_date = models.DateField()
    created_by = models.CharField(max_length=50, null=True)
    modified_date = models.DateField(null=True)
    modified_by = models.CharField(max_length=50, null=True)
    longitude = models.CharField(max_length=50, null=True)
    latitude = models.CharField(max_length=50, null=True)
    active = models.BooleanField(default=1)

class ReferralContact(models.Model):
    referral_contact_id = models.AutoField(primary_key=True)
    referral_company = models.ForeignKey(ReferralCompany, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    website = models.CharField(max_length=100, null=True)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    zipcode = models.CharField(max_length=10, null=True)
    office_number = models.CharField(max_length=15, null=True)
    other_number = models.CharField(max_length=15, null=True)
    fax = models.CharField(max_length=15, null=True)
    email = models.CharField(max_length=50, null=True)
    created_date = models.DateField()
    created_by = models.CharField(max_length=50, null=True)
    modified_date = models.DateField(null=True)
    modified_by = models.CharField(max_length=50, null=True)
    active = models.BooleanField(default=1)

class Client(models.Model):
    client_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    client_acct_number = models.CharField(max_length=15, null=True)
    ssn = models.CharField(max_length=9, null=True)
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=10, null=True)
    height = models.CharField(max_length=10, null=True)
    weight = models.CharField(max_length=10, null=True)
    language = models.ForeignKey(ListLanguage, null=True)
    marital_status = models.ForeignKey(ListMaritalStatus, null=True)
    ethnicity = models.ForeignKey(ListEthnicity, null=True)
    religion = models.ForeignKey(ListReligion, null=True)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    zipcode = models.CharField(max_length=10, null=True)
    home_number = models.CharField(max_length=15, null=True)
    mobile_number = models.CharField(max_length=15, null=True)
    office_number = models.CharField(max_length=15, null=True)
    fax = models.CharField(max_length=15, null=True)
    email = models.CharField(max_length=50, null=True)
    start_of_care = models.DateField(null=True)
    care_manager_user = models.ForeignKey(User, null=True)
    referral_company = models.ForeignKey(ReferralCompany, null=True)
    referral_contact = models.ForeignKey(ReferralContact, null=True)
    client_status = models.ForeignKey(ListClientStatus, null=True)
    status_date = models.DateField(null=True)
    status_note = models.CharField(max_length=400, null=True)
    created_date = models.DateField()
    created_by = models.CharField(max_length=50, null=True)
    modified_date = models.DateField(null=True)
    modified_by = models.CharField(max_length=50, null=True)
    longitude = models.CharField(max_length=50, null=True)
    latitude = models.CharField(max_length=50, null=True)
    active = models.BooleanField(default=1)

class Caregiver(models.Model):
    caregiver_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    employee_id = models.CharField(max_length=50, null=True)
    employee_type = models.ForeignKey(ListEmployeeType, null=True)
    ssn = models.CharField(max_length=9, null=True)
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=10, null=True)
    height = models.CharField(max_length=10, null=True)
    weight = models.CharField(max_length=10, null=True)
    language = models.ForeignKey(ListLanguage, null=True)
    marital_status = models.ForeignKey(ListMaritalStatus, null=True)
    ethnicity = models.ForeignKey(ListEthnicity, null=True)
    religion = models.ForeignKey(ListReligion, null=True)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    zipcode = models.CharField(max_length=10, null=True)
    home_number = models.CharField(max_length=15, null=True)
    mobile_number = models.CharField(max_length=15, null=True)
    office_number = models.CharField(max_length=15, null=True)
    fax = models.CharField(max_length=15, null=True)
    email = models.CharField(max_length=50, null=True)
    hire_date = models.DateField(null=True)
    termination_date = models.DateField(null=True)
    supervisor_user = models.ForeignKey(User, null=True)
    referral_company = models.ForeignKey(ReferralCompany, null=True)
    referral_contact = models.ForeignKey(ReferralContact, null=True)
    staff_status = models.ForeignKey(ListStaffStatus, null=True)
    status_date = models.DateField(null=True)
    status_note = models.CharField(max_length=400, null=True)
    created_date = models.DateField()
    created_by = models.CharField(max_length=50, null=True)
    modified_date = models.DateField(null=True)
    modified_by = models.CharField(max_length=50, null=True)
    longitude = models.CharField(max_length=50, null=True)
    latitude = models.CharField(max_length=50, null=True)
    active = models.BooleanField(default=1)